### ISSUE TITLE
Add LICENSE file?

### ISSUE THREAD

**Issue by jonrimmer** [myplanetdigital/angular-color-picker#7]
Is it possible to add a LICENSE file to the project? I would like to use angular-color-picker in my job, but I am not able to do so without a clearer copyright situation. The package.json says "MIT", but I don't think that alone would be legally sufficient.

**Comment by atesgoral** [comment]
Added license file:

c9e597e48761d7b579c2c40520345742e2e0f42d

Please use verison 1.0.3 which includes this file.

Thanks for the reminder @JonRimmer!

**Comment by jonrimmer** [comment]
:+1:
